- name: install python and simplejson
  hosts: all
  gather_facts: false
  tasks:
    - raw: |
            # If using root user -- ensure sudo exists.
            if [[ $UID -e 0 ]]; then
              apt-get install --yes sudo
            fi
            # Now install python
            sudo apt-get install --yes python-simplejson
