- name: bootstrap
  hosts: all
  gather_facts: false
  tasks:
    - name: determine packet manager
      raw: |
          which yum > /dev/null 2> /dev/null && echo yum
          which apt-get > /dev/null 2> /dev/null && echo apt-get
      ignore_errors: yes
      register: packet_manager

    - name: raw sudo and python install (debian|ubuntu)
      raw: |
            export DEBIAN_FRONTEND=noninteractive
            if [[ $UID -ne 0 ]]; then
                PREFIX=sudo
            fi
            # Refresh apt-cache
            ${PREFIX} sed -i -e 's/http\.us/ftp\.lt/g' /etc/apt/sources.list;
            ${PREFIX} apt-get update
            # If using root user -- ensure sudo exists and knows the hostname
            if [[ $UID -eq 0 ]]; then
              apt-get install --yes sudo
              grep -n 127.0.1.1 /etc/hosts > /dev/null
              if [[ $? -eq 0 ]]; then
                #replace the line
                sed -i "/127.0.1.1/c \
                127.0.1.1 `hostname`.local `hostname`" /etc/hosts
              else
                #insert the line
                sed -i "/127.0.0.1/a \
                127.0.1.1 `hostname`.local `hostname`" /etc/hosts
              fi
            fi
            # Now install python, aptitude
            sudo apt-get install --yes python-simplejson python-apt aptitude
      when: '"apt-get" in packet_manager.stdout'

    - name: raw python install (centos|redhat)
      raw: |
            if [[ $UID -ne 0 ]]; then
                PREFIX=sudo
            fi
            # Refresh yum cache
            ${PREFIX} yum update
            ${PREFIX} yum install --assumeyes python-simplejson
      when: '"yum" in packet_manager.stdout'
