- name: bootstrap
  hosts: all
  gather_facts: false
  tasks:
    - name: raw sudo and python install
      raw: |
            # If using root user -- ensure sudo exists.
            if [[ $UID -eq 0 ]]; then
              apt-get install --yes sudo
            fi
            # Now install python
            sudo apt-get install --yes python-simplejson
