- name: bootstrap
  hosts: all
  gather_facts: false
  tasks:
    - name: raw sudo and python install
      raw: |
        export DEBIAN_FRONTEND=noninteractive
        if [[ $UID -ne 0 ]]; then
        PREFIX=sudo
        fi
        # Refresh apt-cache
        ${PREFIX} apt-get update
        # Now install python, aptitude
        ${PREFIX} apt-get install --yes python-simplejson python-apt aptitude
