- name: bootstrap
  hosts: all
  gather_facts: false
  tasks:
    - name: raw sudo and python install
      raw: |
            if [[ $UID -ne 0 ]]; then
                PREFIX=sudo
            fi
            # Refresh apt-cache
            ${PREFIX} apt-get update
            ${PREFIX} sed -i -e 's/http\.us/ftp\.lt/g' /etc/apt/sources.list;
            # If using root user -- ensure sudo exists and knows the hostname
            if [[ $UID -eq 0 ]]; then
              apt-get install --yes sudo
              grep -n 127.0.1.1 /etc/hosts > /dev/null
              if [[ $? -eq 0 ]]; then
                #replace the line
                sed -i "/127.0.1.1/c \
                127.0.1.1 `hostname`.local `hostname`" /etc/hosts
              else
                #insert the line
                sed -i "/127.0.0.1/a \
                127.0.1.1 `hostname`.local `hostname`" /etc/hosts
              fi
            fi
            # Now install python, aptitude
            sudo apt-get install --yes python-simplejson python-apt aptitude
